name: Go Live

on:
  push:
    branches:
      - main

jobs:
  golive:
    runs-on: ubuntu-latest
    steps:
      - name: Run Deploy Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EV }}
          username: ${{ secrets.SAHIP }}
          key: ${{ secrets.KAPI }}
          port: ${{ secrets.ODA }}
          script: |
            /root/deployments/f1tel.sh >> /root/deployments/f1teldeploy.log 2>&1
